package com.galileo.position;

import javax.measure.Quantity;
import javax.measure.quantity.Length;

import com.galileo.internal.MeasureUtil;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class ECEF {

	private final Quantity<Length> x;
	private final Quantity<Length> y;
	private final Quantity<Length> z;

	public ECEF(Quantity<Length> x, Quantity<Length> y, Quantity<Length> z) {
		this.x = x;
		this.y = y;
		this.z = z;
	}

	public Quantity<Length> getX() {
		return x;
	}

	public Quantity<Length> getY() {
		return y;
	}

	public Quantity<Length> getZ() {
		return z;
	}

	public Quantity<Length> directDistanceTo(ECEF ecef) {
		return MeasureUtil.norm(x.subtract(ecef.x), y.subtract(ecef.y), z.subtract(ecef.z));
	}

	public Quantity<Length> distanceToEarthCenter() {
		return MeasureUtil.norm(x, y, z);
	}

}
